### PR TITLE
- Fixed a couple errors when making shopsigns is on items

### PR DESCRIPTION
**Pull request by KillerOfPie**
- If item with no meta is given it will choose first item and copy meta
- Above does not work for iTrade
- Also fixed potion names

### CODE REVIEW

**Comment by SparklingComet** [comment]
This PR contains fixes for #24 .

**Comment by KillerOfPie** [comment]
I'm going to merge this since its already tested and i want to start work on new branches

**Comment by SparklingComet** [comment]
Excellent. I assume the `Custom-Items` branch can be deleted safely..?

**Comment by KillerOfPie** [comment]
Ya

**Pull request merged**
