### PR TITLE
Added support for durability via `:` separator.

### PR DESCRIPTION
**Pull request by waffleston**
This solves Issue #1.

Changes in brief:
* Added (int) durability1, durability2.
* `:` separator on sign.
* Checks to make sure durability for the stack matches the sign.
* Default durability is 0

Extra:
* Ensures that armor/weapons have full durability unless specified.

### CODE REVIEW

**Comment by waffleston** [comment]
I'd also like to point out that durability of armor counts up from 0, ex:
Game durability of 292/295 will be getDurability() of 3.

**Review by KillerOfPie — COMMENTED** [review]
Doesn't check chest with durability on sign create.
That's the only problem i can see atm.

**Comment by waffleston** [comment]
Would you mind clarifying what that means?

**Comment by KillerOfPie** [comment]
When the signs are created it checks to see if the item is in the chest, you didn't add durability so it will just check for the material

**Review by KillerOfPie — APPROVED** [review]
Looks good to me, hard to tell on phone though.

**Comment by KillerOfPie** [comment]
Also not that it matters, but since you already checked if they were equal you didn't have to change where it was setting the durability from(although it changes nothing either way)

**Comment by SparklingComet** [comment]
Looks good to me. Have you tested the changes?

**Comment by KillerOfPie** [comment]
I have not tested it yet

**Comment by SparklingComet** [comment]
Alright, I'll merge this as soon as one of you confirms it's working.

**Comment by SparklingComet** [comment]
@KillerOfPie You mentioned you already merged @waffleston code in #5 ?

**Comment by KillerOfPie** [comment]
Yes, ~#5~ #6 has all of it and is good to go

**Comment by SparklingComet** [comment]
@KillerOfPie I meant #6, sorry. You said you were implementing this PR's code.
([Comment](https://github.com/SparklingComet/TradeShop/pull/6#issuecomment-316330033))

**Comment by KillerOfPie** [comment]
Yes everything should be in #6

**Comment by SparklingComet** [comment]
> Yes everything should be in #6

Alright, thanks.
Closing.

**Pull request closed without merging**
