### PR TITLE
Restrain power of TSAF (addons cannot override protection config)

### PR DESCRIPTION
**Pull request by SparklingComet**
[contributing]: https://github.com/SparklingComet/TradeShop/blob/master/.github/CONTRIBUTING.md

## Pull Request Etiquette

There are several guidelines you should follow in order for your Pull Request to be merged.
Replace `[ ]` with `[x]` to cross the checkbox.

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

> It is sometimes better to include more changes in a single commit. 
  If you find yourself having an overwhelming amount of commits, you
  can **rebase** your branch.

## Changes

I don't like how the TSAF handles hopper protection. More specifically, how it can override `isForbidden`. This PR changes that, so that what users choose in the tradeshop config is final.

### CODE REVIEW

**Comment by SparklingComet** [comment]
@KillerOfPie do you agree with the philosophy behind the change?

**Comment by SparklingComet** [comment]
This needs to be done again after #111 .

**Comment by KillerOfPie** [comment]
Nothing in #111 was changed by this

**Comment by SparklingComet** [comment]
Merging PR with branch `2.3.2` and pushing the burden of testing onto #111 .

**Pull request merged**
