### PR TITLE
Fix for filled chest bug

### PR DESCRIPTION
**Pull request by KillerOfPie**
This should fix the bug for the filled chest bug, please test when you find out how to recreate it.

### CODE REVIEW

**Comment by KillerOfPie** [comment]
@waafleston try this and see if it fixes for your problem.

**Comment by KillerOfPie** [comment]
@waffleston ^

**Comment by waffleston** [comment]
It did not appear to solve the problem.  It still allows the trade to happen.

Recreation:
Fill chest all the way with stacks of 64 stone.
```
[Trade]
1 stone
1 dirt
```
Right clicking results in one stone being deducted from chest but no dirt - should prevent trade.

**Comment by KillerOfPie** [comment]
@waffleston should work now

**Comment by KillerOfPie** [comment]
@SparklingComet This pull fixes both issues were having and cleans up a bit(also fixes some wierd indenting that existed)
Uses @waffleston code for the data value fixes

Both issues tested and confirmed working

**Comment by KillerOfPie** [comment]
Now its ready

**Comment by SparklingComet** [comment]
Assuming that your tests went well, I will now merge this.
Thanks for the hard work :)

**Pull request merged**
